name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sphinx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: python:3.9
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: |
          apt-get update
          apt-get install -y pandoc
          pip install --upgrade pip
          pip install poetry sphinx sphinx_rtd_theme nbsphinx
      - name: make
        run: |
          poetry export -f requirements.txt > requirements.txt
          pip install -r requirements.txt
          sphinx-apidoc -f -o ./sphinx screcode
          sphinx-build ./sphinx ./docs
          cp -r docs ../public
          poetry build
          mv dist/*.whl ../public/
      - name: pages
        uses: actions/upload-artifact@v3
        with:
          path: public
  deploy:
    needs: sphinx
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1