name: Deploy Documentation

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          apt-get update
          apt-get install -y pandoc

      - name: Install Python packages
        run: |
          pip install --upgrade pip
          pip install poetry sphinx sphinx_rtd_theme nbsphinx

      - name: Build documentation and package
        run: |
          cd python
          poetry export -f requirements.txt --output requirements.txt
          pip install -r requirements.txt
          sphinx-apidoc -f -o ./sphinx screcode
          sphinx-build ./sphinx ../public
          poetry build
          cp dist/*.whl ../public/

      - name: Check public contents
        run: ls -lhR public

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public

  deploy:
    needs: build-docs
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
