name: Deploy
on: [push]
jobs:
  pypi:
    runs-on: ubuntu-latest
    container:
        image: python:3.7
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: pip install poetry
      - name: build
        run: |
          poetry version $(grep "^version" pyproject.toml | grep -o "[0-9]\.[0-9]\.[0-9]").dev$(date +"%Y%m%d%H%M")
          poetry build -f wheel
      - name: publish
        env:
          PYPI_ORG_TOKEN: ${{ secrets.PYPI_ORG_TOKEN }}
        run: poetry publish --username __token__ --password ${PYPI_ORG_TOKEN} --no-ansi -n -v
  sphinx:
    runs-on: ubuntu-latest
    container:
        image: python:3.7
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: |
          apt-get update
          apt-get install -y pandoc
          pip install poetry sphinx sphinx_rtd_theme nbsphinx
      - name: make
        run: |
          poetry export -f requirements.txt --output requirements.txt 
          pip install -r requirements.txt 
          sphinx-apidoc -f -o ./sphinx screcode
          sphinx-build ./sphinx ./docs
          cp -r docs ../public
          poetry build
          mv dist/*.whl ../public/
      - name: pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
          force_orphan: true