name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Upload artifact
      uses: actions/upload-artifact@v3 # Ensure this action is correctly referenced
      with:
        name: build-artifact
        path: build/
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3  # Updated to latest version

    - name: Build
      run: |
        # Your build commands here

    - name: Upload Build Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: build-artifacts
        path: path/to/artifacts  # Ensure this path is correct and exists
  sphinx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: python:3.9
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: |
          apt-get update
          apt-get install -y pandoc
          pip install --upgrade pip
          pip install poetry sphinx sphinx_rtd_theme nbsphinx
      - name: make
        run: |
          poetry export -f requirements.txt --output requirements.txt 
          pip install -r requirements.txt 
          sphinx-apidoc -f -o ./sphinx screcode
          sphinx-build ./sphinx ./docs
          cp -r docs ../public
          poetry build
          mv dist/*.whl ../public/
      - name: pages
        uses: actions/upload-pages-artifact@v1
        with:
          path: public