name: Github Pages
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sphinx:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    container:
      image: python:3.11
    steps:
      - uses: actions/checkout@v1
      - name: install
        run: |
          apt-get update
          apt-get install -y pandoc
          pip install --upgrade pip
          pip install poetry ipython
          poetry self add poetry-plugin-export
          poetry export -f requirements.txt --output requirements.txt --without-hashes --with=ghpages
          pip install -r requirements.txt
      - name: build
        run: |
          cp ./README.md ./sphinx/source
          cp ./scegot/tutorial.ipynb ./sphinx/source
          sphinx-apidoc -f -o ./sphinx/source ./scegot
          sphinx-build ./sphinx/source ./docs
          cp -r docs ./public
      - name: pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: public
  deploy:
    needs: sphinx
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4